table dim_vehiculo
	lineageTag: 91280e11-6c32-452a-9d9d-c3f6842e719d

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 32855d03-2975-4c07-a0ef-398fe716ff4e
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: d8a86d3b-7973-4a8f-90e4-88070d798bae
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: cf49219a-24f9-4b63-b44a-a59abda1012c
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: d36a3eff-5f59-4197-9a6f-1410fdf17e7b
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column año_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: cd1a4b69-19ef-498b-9554-c0bf1ca08d4a
		summarizeBy: none
		sourceColumn: año_vehiculo

		annotation SummarizationSetBy = Automatic

	partition dim_vehiculo = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("\\Mac\Home\Downloads\VentasVehiculos.xlsx"), null, true),
				    dim_vehiculo_Table = Source{[Item="dim_vehiculo",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dim_vehiculo_Table,{{"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"año_vehiculo", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

